# fly.toml app configuration file generated for fly-minecraft-server on 2024-12-31T09:34:37Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fly-minecraft-server'
primary_region = 'mad'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 4
  memory_mb = 2048
